<#--

Copyright (C) 2011 Markus Junginger, greenrobot (http://greenrobot.de)     
                                                                           
This file is part of greenDAO Generator.
                                                                           
greenDAO Generator is free software: you can redistribute it and/or modify 
it under the terms of the GNU General Public License as published by       
the Free Software Foundation, either version 3 of the License, or          
(at your option) any later version.                                        
greenDAO Generator is distributed in the hope that it will be useful,      
but WITHOUT ANY WARRANTY; without even the implied warranty of             
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              
GNU General Public License for more details.                               
                                                                           
You should have received a copy of the GNU General Public License          
along with greenDAO Generator.  If not, see <http://www.gnu.org/licenses/>.

-->
<#assign toBindType = {"Boolean":"Long", "Byte":"Long", "Short":"Long", "Int":"Long", "Long":"Long", "Float":"Double", "Double":"Double", "String":"String", "ByteArray":"Blob" }/>
<#assign toCursorType = {"Boolean":"Short", "Byte":"Short", "Short":"Short", "Int":"Int", "Long":"Long", "Float":"Float", "Double":"Double", "String":"String", "ByteArray":"Blob" }/>
<#assign toParcelType = {"Boolean":"Value", "boolean":"Byte", "Byte":"Value", "byte":"Byte", "Integer":"Value", "int":"Int", "Long":"Value", "long":"Long", "Float":"Value", "float":"Float", "Double":"Value", "double":"Double", "String":"String", "Byte[]":"ByteArray" }/>
<#assign complexTypes = ["String", "ByteArray", "Date"]/>
package ${entity.javaPackage};

<#if entity.toManyRelations?has_content>
import java.util.List;
import java.util.Collections;
</#if>
<#if entity.enums?has_content>
import de.greenrobot.dao.DaoEnum;
import java.util.Map;
import java.util.HashMap;

</#if>
<#list entity.properties as property>
    <#if property.anEnum && entity.className != property.entityEnum.entity.className>
import ${entity.javaPackage}.${property.entityEnum.entity.className}<#if !property.entityEnum.entity.anEnum>.${property.entityEnum.enumName}</#if>;
    </#if>
</#list>
<#if entity.implementParcelable>
import android.os.Parcel;
import android.os.Parcelable;
</#if>
<#if entity.aBaseEntity>
import de.greenrobot.dao.sync.GreenSyncBase;
</#if>
<#if entity.active>
import de.greenrobot.dao.DaoException;

</#if>
<#if entity.additionalImportsEntity?has_content>
<#list entity.additionalImportsEntity as additionalImport>
import ${additionalImport};
</#list>

</#if>
<#if entity.hasKeepSections>
// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
<#if keepIncludes?has_content>${keepIncludes!}</#if>// KEEP INCLUDES END
<#else>
// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
</#if>
/**
 * Entity mapped to table ${entity.tableName}.
 */
public class ${entity.className}<#if
entity.superclass?has_content> extends ${entity.superclass}</#if><#if
entity.interfacesToImplement?has_content> implements <#list entity.interfacesToImplement
as ifc>${ifc}<#if ifc_has_next>, </#if></#list></#if> {

<#list entity.properties as property>
<#if property.notNull && complexTypes?seq_contains(property.propertyType)>
    /** Not-null value. */
</#if>
    private <#if property.transientProperty>transient </#if>${property.javaType} ${property.propertyName};
</#list>

<#if entity.active>
    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient ${entity.classNameDao} myDao;
<#list entity.toOneRelations as toOne>
    private ${toOne.targetEntity.className} ${toOne.name};
<#if toOne.useFkProperty>
    private ${toOne.resolvedKeyJavaType[0]} ${toOne.name}__resolvedKey;
<#else>
    private boolean ${toOne.name}__refreshed;
</#if>
</#list>
<#list entity.toManyRelations as toMany>
    private List<${toMany.targetEntity.className}> ${toMany.name};
</#list>

</#if>
<#if entity.hasKeepSections>
    // KEEP FIELDS - put your custom fields here
${keepFields!}    // KEEP FIELDS END

</#if>
<#if entity.constructors>
    public ${entity.className}() {
    }

<#if entity.propertiesPk?has_content && entity.propertiesPk?size != entity.properties?size>
    public ${entity.className}(<#list entity.propertiesPk as
property><#if property_index != 0 && property.reference>, </#if>${property.javaType} ${property.propertyName}</#list>) {
<#list entity.propertiesPk as property>
        this.${property.propertyName} = ${property.propertyName};
</#list>
    <#if entity.baseEntity??>
        setDerivedEntityType(getClass().getCanonicalName());
    </#if>
    }

</#if>
<#if entity.hasReferenceProperty>
    ${entity.className}(<#list entity.properties as
property>${property.javaType} ${property.propertyName}<#if property_has_next>, </#if></#list>) {
<#list entity.properties as property>
        this.${property.propertyName} = ${property.propertyName};
</#list>
    }

</#if>
    <#assign x = 0>
    public ${entity.className}(<#list entity.properties as
        property><#if !property.reference><#if x != 0>, </#if>${property.javaType} ${property.propertyName}<#assign x = x + 1></#if></#list>) {
    <#list entity.properties as property>
        <#if !property.reference>
        this.${property.propertyName} = ${property.propertyName};
        </#if>
    </#list>
    <#if entity.baseEntity??>
        setDerivedEntityType(getClass().getCanonicalName());
    </#if>
    }

</#if>
<#if entity.active>
    /** called by internal mechanisms, do not call yourself. */
<#if entity.baseEntity??>
    @Override
</#if>
    public void __setDaoSession(DaoSession daoSession) {
        <#if entity.baseEntity??>
        super.__setDaoSession(daoSession);
        </#if>
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.get${entity.classNameDao?cap_first}() : null;
    }

</#if>
<#if entity.aBaseEntity>
    void loadBase(${entity.classNameDao} dao, <#list entity.propertiesPk as
        property><#if property_index != 0>, </#if>${property.javaType} ${property.propertyName}</#list>) {
        myDao = dao;
    <#list entity.propertiesPk as property>
        this.${property.propertyName} = ${property.propertyName};
    </#list>
        myDao.refresh(this);
    }

    void insertBase(${entity.classNameDao} dao) {
        myDao = dao;
        setState(BaseState.CREATE);
        dao.insert(this);
    }

    void updateBase(SyncBaseDao dao) {
        if (state == BaseState.CREATE) return;
        myDao = dao;
        setState(BaseState.UPDATE);
        myDao.update(this);
    }

    void deleteBase(SyncBaseDao dao) {
        myDao = dao;
        setState(BaseState.DELETE);
        myDao.delete(this);
    }

    @Override
    public void clean() {
        setState(BaseState.CLEAN);
    }
</#if>
<#list entity.properties as property>
<#if property.notNull && complexTypes?seq_contains(property.propertyType)>
    /** Not-null value. */
</#if>
    public ${property.javaType} get${property.propertyName?cap_first}() {
        return ${property.propertyName};
    }

<#if property.notNull && complexTypes?seq_contains(property.propertyType)>
    /** Not-null value; ensure this value is available before it is saved to the database. */
</#if>
    public void set${property.propertyName?cap_first}(${property.javaType} ${property.propertyName}) {
        this.${property.propertyName} = ${property.propertyName};
    }

</#list>
<#list entity.enums as enum>
    public enum ${enum.enumName} implements DaoEnum {
        <#list enum.values as value>
        ${value.name}(${value.tag})<#if value_has_next>,<#else>;</#if>
        </#list>

        private static final Map<Long, ${enum.enumName}> intToTypeMap = new HashMap<Long, ${enum.enumName}>();

        static {
            for (${enum.enumName} type : ${enum.enumName}.values()) {
                intToTypeMap.put(type.value, type);
            }
        }

        public static ${enum.enumName} fromInt(long i) {
            ${enum.enumName} type = intToTypeMap.get(Long.valueOf(i));
            return type;
        }

        private final long value;

        private ${enum.enumName}(long value) {
            this.value = value;
        }

        @Override
        public long getValue() {
            return value;
        }
    }

</#list>
<#--
##########################################
########## To-One Relations ##############
##########################################
-->
<#list entity.toOneRelations as toOne>
    /** To-one relationship, resolved on first access. */
    public ${toOne.targetEntity.className} get${toOne.name?cap_first}() {
<#if toOne.useFkProperty>
        ${toOne.fkProperties[0].javaType} __key = this.${toOne.fkProperties[0].propertyName};
        if (${toOne.name}__resolvedKey == null || <#--
        --><#if toOne.resolvedKeyUseEquals[0]>!${toOne.name}__resolvedKey.equals(__key)<#--
        --><#else>${toOne.name}__resolvedKey != __key</#if>) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            ${toOne.targetEntity.classNameDao} targetDao = daoSession.get${toOne.targetEntity.classNameDao?cap_first}();
            ${toOne.targetEntity.className} ${toOne.name}New = targetDao.load(__key);
            synchronized (this) {
                ${toOne.name} = ${toOne.name}New;
            	${toOne.name}__resolvedKey = __key;
            }
        }
<#else>
        if (${toOne.name} != null || !${toOne.name}__refreshed) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            ${toOne.targetEntity.classNameDao} targetDao = daoSession.get${toOne.targetEntity.classNameDao?cap_first}();
            targetDao.refresh(${toOne.name});
            ${toOne.name}__refreshed = true;
        }
</#if>
        return ${toOne.name};
    }
<#if !toOne.useFkProperty>

    /** To-one relationship, returned entity is not refreshed and may carry only the PK property. */
    public ${toOne.targetEntity.className} peak${toOne.name?cap_first}() {
        return ${toOne.name};
    }
</#if>

    public void set${toOne.name?cap_first}(${toOne.targetEntity.className} ${toOne.name}) {
<#if toOne.fkProperties[0].notNull>
        if (${toOne.name} == null) {
            throw new DaoException("To-one property '${toOne.fkProperties[0].propertyName}' has not-null constraint; cannot set to-one to null");
        }
</#if>
        synchronized (this) {
            this.${toOne.name} = ${toOne.name};
<#if toOne.useFkProperty>        
            ${toOne.fkProperties[0].propertyName} = <#if !toOne.fkProperties[0].notNull>${toOne.name} == null ? null : </#if>${toOne.name}.get${toOne.targetEntity.pkProperty.propertyName?cap_first}();
            ${toOne.name}__resolvedKey = ${toOne.fkProperties[0].propertyName};
<#else>
            ${toOne.name}__refreshed = true;
</#if>
        }
    }

</#list>
<#--
##########################################
########## To-Many Relations #############
##########################################
-->
<#list entity.toManyRelations as toMany>
    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<${toMany.targetEntity.className}> get${toMany.name?cap_first}() {
        if (${toMany.name} == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            ${toMany.targetEntity.classNameDao} targetDao = daoSession.get${toMany.targetEntity.classNameDao?cap_first}();
            List<${toMany.targetEntity.className}> ${toMany.name}New = targetDao._query${toMany.sourceEntity.className?cap_first}_${toMany.name?cap_first}(<#--
                --><#list toMany.sourceProperties as property>${property.propertyName}<#if property_has_next>, </#if></#list>);
            synchronized (this) {<#-- Check if another thread was faster, we cannot lock while doing the query to prevent deadlocks -->
                if(${toMany.name} == null) {
                    ${toMany.name} = ${toMany.name}New;
                }
            }
        }
        return Collections.unmodifiableList(${toMany.name});
    }

    public void set${toMany.name?cap_first}(List<${toMany.targetEntity.className}> ${toMany.name}) {
        if (${toMany.name} == null) return;

        synchronized (this) {
            for (${toMany.targetEntity.className} item : ${toMany.name}) {
                <#assign x=toMany.sourceProperties?size - 1>
                <#list 0..x as i>
                item.set${toMany.targetProperties[i].propertyName?cap_first}(get${toMany.sourceProperties[i].propertyName?cap_first}());
                </#list>
            }

            this.${toMany.name} = ${toMany.name};
        }
    }

    public void add${toMany.name?cap_first}(${toMany.targetEntity.className} ${toMany.name}) {
        if (${toMany.name} == null) return;

        synchronized (this) {
            <#assign x=toMany.sourceProperties?size - 1>
            <#list 0..x as i>
            ${toMany.name}.set${toMany.targetProperties[i].propertyName?cap_first}(get${toMany.sourceProperties[i].propertyName?cap_first}());
            </#list>
            this.${toMany.name}.add(${toMany.name});
        }
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void reset${toMany.name?cap_first}() {
        ${toMany.name} = null;
    }

</#list>
<#--
##########################################
########## Active entity operations ######
##########################################
-->
<#if entity.active>
    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

</#if>
<#if entity.implementParcelable>
    public ${entity.className}(Parcel in ) {
        readFromParcel(in);
    }

    public static final Parcelable.Creator CREATOR = new Parcelable.Creator() {
        public ${entity.className} createFromParcel(Parcel in) {
            return new ${entity.className}(in);
        }

        public ${entity.className}[] newArray(int size) {
            return new ${entity.className}[size];
        }
    };


    @Override
    public void writeToParcel(Parcel dest, int flags) {
    <#list entity.properties as property>
        <#if property.anEnum>
        dest.writeLong(${property.propertyName}.getValue());
        <#elseif property.javaType == "boolean">
        dest.writeByte((byte) (${property.propertyName} ? 1 : 0));
        <#else>
        dest.write${toParcelType[property.javaType]}(${property.propertyName});
        </#if>
    </#list>
    <#list entity.toOneRelations as toOne>
        dest.writeValue(${toOne.name});
    </#list>
    <#list entity.toManyRelations as toMany>
        dest.writeArray(${toMany.name} != null ? ${toMany.name}.toArray() : null);
    </#list>
    }

    @Override
    public int describeContents() {
        return 0;
    }

    private void readFromParcel(Parcel in) {
    <#list entity.properties as property>
        <#if property.anEnum>
        ${property.propertyName} = ${property.javaType}.fromInt(in.readLong());
        <#elseif property.javaType == "boolean">
        ${property.propertyName} = in.readByte() != 0;
        <#elseif toParcelType[property.javaType] == "Value">
        ${property.propertyName} = (${property.javaType}) in.read${toParcelType[property.javaType]}(ClassLoader.getSystemClassLoader());
        <#else>
        ${property.propertyName} = in.read${toParcelType[property.javaType]}();
        </#if>
    </#list>
    <#list entity.toOneRelations as toOne>
        ${toOne.name} = (${toOne.targetEntity.className}) in.readValue(${toOne.targetEntity.className}.class.getClassLoader());
    </#list>
    <#list entity.toManyRelations as toMany>
        ${toMany.name} = in.readArrayList(${toMany.targetEntity.className}.class.getClassLoader());
    </#list>
    }
</#if>
<#if entity.hasKeepSections>
    // KEEP METHODS - put your custom methods here
${keepMethods!}    // KEEP METHODS END

</#if>
}