package de.greenrobot.daoexample.database;

import de.greenrobot.dao.DaoEnum;
import java.util.HashMap;
import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

public enum BaseState implements DaoEnum {
    CREATE(1),
    UPDATE(2),
    DELETE(3),
    CLEAN(3);

    private static final Map<Long, BaseState> intToTypeMap = new HashMap<Long, BaseState>();

    static {
        for (BaseState type : BaseState.values()) {
            intToTypeMap.put(type.value, type);
        }
    }

    public static BaseState fromInt(long i) {
        BaseState type = intToTypeMap.get(Long.valueOf(i));
        return type;
    }

    private final long value;

    private BaseState(long value) {
        this.value = value;
    }

    @Override
    public long getValue() {
        return value;
    }
}